---
# tasks file for K8s-worker

- debug:
      msg: "Now configuring the worker nodes.."
- name: "Configuring repository for docker"
  yum_repository:
               name: "docker"
               description: "yum repo for docker"
               baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
               gpgcheck: no
- name: "Installing containerd.io"
  package:
                 name: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.4.3-3.1.el7.x86_64.rpm"
                 state: present
                 disable_gpg_check: True
- name: "Installing docker"
  package:
            name: "docker-ce"
            state: present
- name: "Disabling SElinux"
  selinux:
            state: disabled
- name: "Starting and enabling docker service permanently"
  service:
            name: "docker"
            state: started
            enabled: yes
- name: "Configuring repository for K8s"
  yum_repository:
            name: "K8s-repo"
            description: "Repository for K8s"
            baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
            gpgcheck: no
- name: "Installing kubeadm, kubectl and kubelet"
  package:
            name: "kubeadm"
            state: present
- name: "Starting and enabling kubelet service permanently"
  service:
            name: "kubelet"
            state: started
            enabled: yes
- name: "Changing the driver to systemd"
  copy:
            dest: "/etc/docker/daemon.json"
            content: '{
                      "exec-opts": ["native.cgroupdriver=systemd"]
                      }'
- name: "Restarting docker service"
  service:
            name: "docker"
            state: restarted
- name: "Installing iproute-tc software"
  package:
            name: "iproute-tc"
            state: present
- name: "Configuring network"
  copy:
            dest: "/etc/sysctl.d/k8s.conf"
            content:
                - "net.bridge.bridge-nf-call-ip6tables = 1"
                - "net.bridge.bridge-nf-call-iptables = 1"
- name: "Starting sysctl service"
  command: "sudo sysctl --system"
  become_user: root
  become_method: sudo
  become: true
- name: "Joining the K8s worker node to the master node"
  command: "{{ joincmd }}"
- debug:
        msg: "Voila! 2 instances are configured as worker nodes :)"


